variable "ENV" {}
variable "VPC_CIDR_MAIN" {}
variable "PRIVATE_SUBNETS" {}
variable "AZS" {}
variable "VPC_CIDR_ADDON" {}
variable "PUBLIC_SUBNETS" {}
variable "DEFAULT_VPC_ID" {}
variable "DEFAULT_VPC_CIDR" {}
variable "DEFAULT_VPC_ROUTE_TABLE_ID" {}